# Generated by Django 4.2.2 on 2023-06-24 04:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_conference_weather"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conference",
            name="weather",
        ),
    ]
